name: Secret Request

on: [push]

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Make authenticated request
        run: |
          curl -H "Authorization: Bearer ${{ secrets.MY_SECRET }}" https://api.example.com/data
